"""
Core type definitions for the backtesting engine.
Dataclasses for Bar, Signal, Trade, Position, and PlaybookStep.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional


class Direction(Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


class TradeStatus(Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


@dataclass
class Bar:
    """Single OHLCV bar."""
    time: datetime
    open: float
    high: float
    low: float
    close: float
    tick_volume: int = 0
    spread: int = 0

    @property
    def is_bullish(self) -> bool:
        return self.close > self.open

    @property
    def is_bearish(self) -> bool:
        return self.close < self.open

    @property
    def body_high(self) -> float:
        return max(self.open, self.close)

    @property
    def body_low(self) -> float:
        return min(self.open, self.close)

    @property
    def body_size(self) -> float:
        return abs(self.close - self.open)

    @property
    def upper_wick(self) -> float:
        return self.high - self.body_high

    @property
    def lower_wick(self) -> float:
        return self.body_low - self.low

    @property
    def total_range(self) -> float:
        return self.high - self.low

    @property
    def midpoint(self) -> float:
        return (self.high + self.low) / 2.0


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    strategy_id: str
    direction: Direction
    entry_price: float
    stop_loss: float
    take_profit: float
    timestamp: datetime
    symbol: str
    order_type: OrderType = OrderType.MARKET
    risk_reward: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if self.stop_loss and self.take_profit and self.entry_price:
            risk = abs(self.entry_price - self.stop_loss)
            reward = abs(self.take_profit - self.entry_price)
            self.risk_reward = round(reward / risk, 2) if risk > 0 else 0.0


@dataclass
class StepRecord:
    """A single strategy step execution record."""
    step_name: str
    step_number: int
    timestamp: datetime
    price_level: float
    timeframe: str
    description: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Trade:
    """A completed or open trade with full audit trail."""
    id: int
    strategy_id: str
    symbol: str
    direction: Direction
    entry_time: datetime
    entry_price: float
    stop_loss: float
    take_profit: float
    exit_time: Optional[datetime] = None
    exit_price: Optional[float] = None
    pnl: float = 0.0
    pnl_pips: float = 0.0
    pnl_usd: float = 0.0
    risk_reward_achieved: float = 0.0
    status: TradeStatus = TradeStatus.OPEN
    steps: list[StepRecord] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def close(
        self,
        exit_time: datetime,
        exit_price: float,
        pip_value: float = 0.0001,
        lot_size: float = 0.01,
        pip_value_usd: float = 10.0,
    ):
        """Close the trade and calculate price + USD PnL."""
        self.exit_time = exit_time
        self.exit_price = exit_price
        self.status = TradeStatus.CLOSED

        if self.direction == Direction.LONG:
            self.pnl = exit_price - self.entry_price
        else:
            self.pnl = self.entry_price - exit_price

        if pip_value > 0:
            self.pnl_pips = self.pnl / pip_value

        self.pnl_usd = self.pnl_pips * pip_value_usd * lot_size

        risk = abs(self.entry_price - self.stop_loss)
        if risk > 0:
            self.risk_reward_achieved = round(self.pnl / risk, 2)


@dataclass
class Position:
    """An open position being tracked by the portfolio."""
    trade: Trade
    lot_size: float = 0.01
    current_sl: float = 0.0
    current_tp: float = 0.0
    break_even_applied: bool = False

    def __post_init__(self):
        self.current_sl = self.trade.stop_loss
        self.current_tp = self.trade.take_profit

    def move_sl_to_breakeven(self):
        """Move stop loss to entry price."""
        self.current_sl = self.trade.entry_price
        self.break_even_applied = True

    def update_sl(self, new_sl: float):
        """Update stop loss level."""
        self.current_sl = new_sl

    def is_sl_hit(self, bar: Bar) -> bool:
        """Check if stop loss was hit during this bar."""
        if self.trade.direction == Direction.LONG:
            return bar.low <= self.current_sl
        else:
            return bar.high >= self.current_sl

    def is_tp_hit(self, bar: Bar) -> bool:
        """Check if take profit was hit during this bar."""
        if self.trade.direction == Direction.LONG:
            return bar.high >= self.current_tp
        else:
            return bar.low <= self.current_tp


@dataclass
class PlaybookStep:
    """A single step in a strategy's playbook for UI display."""
    step_number: int
    title: str
    description: str
    timeframe: str
    conditions: list[str] = field(default_factory=list)
    key_levels: list[str] = field(default_factory=list)


@dataclass
class BacktestConfig:
    """Configuration for a backtest run."""
    strategy_id: str
    symbol: str
    start_date: datetime
    end_date: datetime
    initial_balance: float = 10000.0
    risk_per_trade: float = 0.01  # 1% risk
    spread_pips: float = 1.0
    slippage_pips: float = 0.5
    commission_per_lot: float = 7.0  # USD per round trip


@dataclass
class BacktestResult:
    """Complete results from a backtest run."""
    config: BacktestConfig
    trades: list[Trade] = field(default_factory=list)
    equity_curve: list[dict[str, Any]] = field(default_factory=list)
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    max_drawdown: float = 0.0
    max_drawdown_pct: float = 0.0
    total_pnl: float = 0.0
    sharpe_ratio: float = 0.0
    avg_rr: float = 0.0
    avg_trade_duration: float = 0.0  # in minutes

    def compute_stats(self):
        """Calculate all performance statistics from the trade list."""
        self.total_trades = len(self.trades)
        if self.total_trades == 0:
            return

        winners = [t for t in self.trades if t.metadata.get("pnl_usd", t.pnl_usd) > 0]
        losers = [t for t in self.trades if t.metadata.get("pnl_usd", t.pnl_usd) <= 0]
        self.winning_trades = len(winners)
        self.losing_trades = len(losers)
        self.win_rate = round(self.winning_trades / self.total_trades * 100, 2)

        gross_profit = sum(t.metadata.get("pnl_usd", t.pnl_usd) for t in winners if t.metadata.get("pnl_usd", t.pnl_usd) > 0) if winners else 0
        gross_loss = abs(sum(t.metadata.get("pnl_usd", t.pnl_usd) for t in losers if t.metadata.get("pnl_usd", t.pnl_usd) <= 0)) if losers else 0
        self.profit_factor = round(gross_profit / gross_loss, 2) if gross_loss > 0 else float("inf")

        self.total_pnl = round(sum(t.metadata.get("pnl_usd", t.pnl_usd) for t in self.trades), 2)
        self.avg_rr = round(
            sum(t.risk_reward_achieved for t in self.trades) / self.total_trades, 2
        )

        # Max drawdown from equity curve
        if self.equity_curve:
            peak = self.equity_curve[0].get("equity", self.config.initial_balance)
            max_dd = 0
            for point in self.equity_curve:
                eq = point.get("equity", peak)
                if eq > peak:
                    peak = eq
                dd = peak - eq
                if dd > max_dd:
                    max_dd = dd
            self.max_drawdown = round(max_dd, 2)
            self.max_drawdown_pct = round(
                max_dd / self.config.initial_balance * 100, 2
            ) if self.config.initial_balance > 0 else 0

        # Average trade duration
        durations = []
        for t in self.trades:
            if t.exit_time and t.entry_time:
                dur = (t.exit_time - t.entry_time).total_seconds() / 60
                durations.append(dur)
        self.avg_trade_duration = round(
            sum(durations) / len(durations), 1
        ) if durations else 0

        # Sharpe ratio (simplified daily returns)
        if len(self.equity_curve) > 1:
            returns = []
            for i in range(1, len(self.equity_curve)):
                prev = self.equity_curve[i - 1].get("equity", 0)
                curr = self.equity_curve[i].get("equity", 0)
                if prev > 0:
                    returns.append((curr - prev) / prev)
            if returns:
                import statistics
                mean_ret = statistics.mean(returns)
                std_ret = statistics.stdev(returns) if len(returns) > 1 else 1
                self.sharpe_ratio = round(
                    (mean_ret / std_ret) * (252 ** 0.5), 2
                ) if std_ret > 0 else 0

    def to_dict(self) -> dict:
        """Serialize to JSON-friendly dict."""
        return {
            "config": {
                "strategy_id": self.config.strategy_id,
                "symbol": self.config.symbol,
                "start_date": self.config.start_date.isoformat(),
                "end_date": self.config.end_date.isoformat(),
                "initial_balance": self.config.initial_balance,
                "risk_per_trade": self.config.risk_per_trade,
            },
            "stats": {
                "total_trades": self.total_trades,
                "winning_trades": self.winning_trades,
                "losing_trades": self.losing_trades,
                "win_rate": self.win_rate,
                "profit_factor": self.profit_factor,
                "max_drawdown": self.max_drawdown,
                "max_drawdown_pct": self.max_drawdown_pct,
                "total_pnl": round(self.total_pnl, 2),
                "sharpe_ratio": self.sharpe_ratio,
                "avg_rr": self.avg_rr,
                "avg_trade_duration_mins": self.avg_trade_duration,
            },
            "equity_curve": self.equity_curve,
            "trades": [
                {
                    "id": t.id,
                    "strategy_id": t.strategy_id,
                    "symbol": t.symbol,
                    "direction": t.direction.value,
                    "entry_time": t.entry_time.isoformat(),
                    "entry_price": t.entry_price,
                    "stop_loss": t.stop_loss,
                    "take_profit": t.take_profit,
                    "exit_time": t.exit_time.isoformat() if t.exit_time else None,
                    "exit_price": t.exit_price,
                    "pnl": round(t.pnl, 5),
                    "pnl_pips": round(t.pnl_pips, 1),
                    "pnl_usd": round(t.pnl_usd, 2),
                    "rr_achieved": t.risk_reward_achieved,
                    "status": t.status.value,
                    "steps": [
                        {
                            "step_name": s.step_name,
                            "step_number": s.step_number,
                            "timestamp": s.timestamp.isoformat(),
                            "price_level": s.price_level,
                            "timeframe": s.timeframe,
                            "description": s.description,
                        }
                        for s in t.steps
                    ],
                }
                for t in self.trades
            ],
        }
